-- MySQL Script generated by MySQL Workbench
-- Thu Apr 21 18:38:26 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Admin` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Admin` (
  `idK` INT NOT NULL,
  PRIMARY KEY (`idK`),
  CONSTRAINT `idK`
    FOREIGN KEY (`idK`)
    REFERENCES `mydb`.`Korisnik` (`idK`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DeoGrada`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`DeoGrada` ;

CREATE TABLE IF NOT EXISTS `mydb`.`DeoGrada` (
  `idDeoGrada` INT NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDeoGrada`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Korisnik`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Korisnik` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Korisnik` (
  `idK` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `lozinka` VARCHAR(45) NOT NULL,
  `ime` VARCHAR(45) NOT NULL,
  `prezime` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idK`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ljubimac`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Ljubimac` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Ljubimac` (
  `idLjubimac` INT NOT NULL AUTO_INCREMENT,
  `ime` VARCHAR(45) NOT NULL,
  `starost` INT NOT NULL,
  `idR` INT NOT NULL,
  `pol` TINYINT(1) NOT NULL,
  `parenje` TINYINT(1) NOT NULL,
  `opis` VARCHAR(300) NOT NULL,
  `idK` INT NOT NULL,
  `slika` BLOB NOT NULL,
  PRIMARY KEY (`idLjubimac`),
  INDEX `idR_idx` (`idR` ASC) VISIBLE,
  INDEX `idK_idx` (`idK` ASC) VISIBLE,
  CONSTRAINT `idR`
    FOREIGN KEY (`idR`)
    REFERENCES `mydb`.`RasaPasa` (`idR`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idK`
    FOREIGN KEY (`idK`)
    REFERENCES `mydb`.`Vlasnik` (`idK`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ocena`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Ocena` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Ocena` (
  `idOcena` INT NOT NULL AUTO_INCREMENT,
  `ocena` INT NOT NULL,
  `idKOcenjuje` INT NOT NULL,
  `idKOcenjen` INT NOT NULL,
  `opis` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`idOcena`),
  INDEX `idKOcenjen_idx` (`idKOcenjen` ASC) VISIBLE,
  INDEX `idKOcenjuje_idx` (`idKOcenjuje` ASC) VISIBLE,
  CONSTRAINT `idKOcenjen`
    FOREIGN KEY (`idKOcenjen`)
    REFERENCES `mydb`.`Korisnik` (`idK`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idKOcenjuje`
    FOREIGN KEY (`idKOcenjuje`)
    REFERENCES `mydb`.`Korisnik` (`idK`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RasaPasa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`RasaPasa` ;

CREATE TABLE IF NOT EXISTS `mydb`.`RasaPasa` (
  `idR` INT NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idR`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Setac`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Setac` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Setac` (
  `idK` INT NOT NULL,
  `godine` INT NOT NULL,
  `telefon` VARCHAR(13) NOT NULL,
  `pol` TINYINT(1) NOT NULL,
  `opis` VARCHAR(300) NOT NULL,
  `idDeoGrada` INT NOT NULL,
  `slika` BLOB NOT NULL,
  PRIMARY KEY (`idK`),
  INDEX `idDeoGrada_idx` (`idDeoGrada` ASC) VISIBLE,
  CONSTRAINT `idK`
    FOREIGN KEY (`idK`)
    REFERENCES `mydb`.`Korisnik` (`idK`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idDeoGrada`
    FOREIGN KEY (`idDeoGrada`)
    REFERENCES `mydb`.`DeoGrada` (`idDeoGrada`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Setnja`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Setnja` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Setnja` (
  `idSetnja` INT NOT NULL AUTO_INCREMENT,
  `datum` DATE NOT NULL,
  `vremeOd` TIME NOT NULL,
  `vremeDo` TIME NOT NULL,
  `cena` INT NOT NULL,
  `maksLjubimaca` INT NOT NULL,
  `idDeoGrada` INT NOT NULL,
  `idK` INT NOT NULL,
  PRIMARY KEY (`idSetnja`),
  INDEX `idDeoGrada_idx` (`idDeoGrada` ASC) VISIBLE,
  INDEX `idK_idx` (`idK` ASC) VISIBLE,
  CONSTRAINT `idDeoGrada`
    FOREIGN KEY (`idDeoGrada`)
    REFERENCES `mydb`.`DeoGrada` (`idDeoGrada`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idK`
    FOREIGN KEY (`idK`)
    REFERENCES `mydb`.`Setac` (`idK`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vlasnik`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Vlasnik` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Vlasnik` (
  `idK` INT NOT NULL,
  `godine` INT NOT NULL,
  `pol` TINYINT(1) NOT NULL,
  `telefon` VARCHAR(13) NOT NULL,
  `opis` VARCHAR(300) NOT NULL,
  `idDeoGrada` INT NOT NULL,
  `slika` BLOB NOT NULL,
  PRIMARY KEY (`idK`),
  INDEX `idDeoGrada_idx` (`idDeoGrada` ASC) VISIBLE,
  CONSTRAINT `idK`
    FOREIGN KEY (`idK`)
    REFERENCES `mydb`.`Korisnik` (`idK`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idDeoGrada`
    FOREIGN KEY (`idDeoGrada`)
    REFERENCES `mydb`.`DeoGrada` (`idDeoGrada`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ZahtevZaParenje`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ZahtevZaParenje` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ZahtevZaParenje` (
  `idZahtevZaParenje` INT NOT NULL AUTO_INCREMENT,
  `idSalje` INT NOT NULL,
  `idPrima` INT NOT NULL,
  `kada` TIME NOT NULL,
  `prihvacen_odbijen` TINYINT(1) NULL,
  PRIMARY KEY (`idZahtevZaParenje`),
  INDEX `idKSalje_idx` (`idSalje` ASC) VISIBLE,
  INDEX `idKPrima_idx` (`idPrima` ASC) VISIBLE,
  CONSTRAINT `idKSalje`
    FOREIGN KEY (`idSalje`)
    REFERENCES `mydb`.`Ljubimac` (`idLjubimac`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idKPrima`
    FOREIGN KEY (`idPrima`)
    REFERENCES `mydb`.`Ljubimac` (`idLjubimac`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ZahtevZaSetnju`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ZahtevZaSetnju` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ZahtevZaSetnju` (
  `idZahteviZaSetnju` INT NOT NULL AUTO_INCREMENT,
  `idSetnja` INT NOT NULL,
  `idLjubimac` INT NOT NULL,
  `prihvacen_odbijen` TINYINT(1) NULL,
  `kada` TIME NOT NULL,
  PRIMARY KEY (`idZahteviZaSetnju`),
  INDEX `idSetnja_idx` (`idSetnja` ASC) VISIBLE,
  INDEX `idLjubimac_idx` (`idLjubimac` ASC) VISIBLE,
  CONSTRAINT `idSetnja`
    FOREIGN KEY (`idSetnja`)
    REFERENCES `mydb`.`Setnja` (`idSetnja`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idLjubimac`
    FOREIGN KEY (`idLjubimac`)
    REFERENCES `mydb`.`Ljubimac` (`idLjubimac`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
